# Generated by Django 5.2.8 on 2025-12-31 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contributionType', models.CharField(max_length=20)),
                ('imageName', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('addres', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default=0, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
