# Generated by Django 5.2.8 on 2025-12-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdata',
            name='image',
        ),
        migrations.AddField(
            model_name='donationdata',
            name='imageName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
