# Generated by Django 5.2.8 on 2025-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationdata_accepted_by_donationdata_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdata',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donationdata',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donationdata',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
