# Generated by Django 5.2.8 on 2025-12-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationdata_address_donationdata_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdata',
            old_name='address',
            new_name='addres',
        ),
    ]
