# Generated by Django 5.2.8 on 2025-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_rename_address_donationdata_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
